// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: customer.proto

package customer

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerService_CreateOnlineBusiness_FullMethodName              = "/customer.CustomerService/CreateOnlineBusiness"
	CustomerService_UpdateCorporateCustomerNationalID_FullMethodName = "/customer.CustomerService/UpdateCorporateCustomerNationalID"
	CustomerService_SetCustomerAsIndividual_FullMethodName           = "/customer.CustomerService/SetCustomerAsIndividual"
	CustomerService_UpdateBusinessInfo_FullMethodName                = "/customer.CustomerService/UpdateBusinessInfo"
	CustomerService_UpdateFinancialData_FullMethodName               = "/customer.CustomerService/UpdateFinancialData"
	CustomerService_ApproveBusiness_FullMethodName                   = "/customer.CustomerService/ApproveBusiness"
)

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Customer service definition
type CustomerServiceClient interface {
	// Create Online Business
	CreateOnlineBusiness(ctx context.Context, in *CreateOnlineBusinessRequest, opts ...grpc.CallOption) (*CreateOnlineBusinessResponse, error)
	// Update Corporate Customer National ID
	UpdateCorporateCustomerNationalID(ctx context.Context, in *UpdateCorporateCustomerNationalIDRequest, opts ...grpc.CallOption) (*UpdateCorporateCustomerNationalIDResponse, error)
	// Set Customer As Individual
	SetCustomerAsIndividual(ctx context.Context, in *SetCustomerAsIndividualRequest, opts ...grpc.CallOption) (*SetCustomerAsIndividualResponse, error)
	// Update Business Info
	UpdateBusinessInfo(ctx context.Context, in *UpdateBusinessInfoRequest, opts ...grpc.CallOption) (*UpdateBusinessInfoResponse, error)
	// Update Financial Data
	UpdateFinancialData(ctx context.Context, in *UpdateFinancialDataRequest, opts ...grpc.CallOption) (*UpdateFinancialDataResponse, error)
	// Approve Business
	ApproveBusiness(ctx context.Context, in *ApproveBusinessRequest, opts ...grpc.CallOption) (*ApproveBusinessResponse, error)
}

type customerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerServiceClient(cc grpc.ClientConnInterface) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) CreateOnlineBusiness(ctx context.Context, in *CreateOnlineBusinessRequest, opts ...grpc.CallOption) (*CreateOnlineBusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOnlineBusinessResponse)
	err := c.cc.Invoke(ctx, CustomerService_CreateOnlineBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) UpdateCorporateCustomerNationalID(ctx context.Context, in *UpdateCorporateCustomerNationalIDRequest, opts ...grpc.CallOption) (*UpdateCorporateCustomerNationalIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCorporateCustomerNationalIDResponse)
	err := c.cc.Invoke(ctx, CustomerService_UpdateCorporateCustomerNationalID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) SetCustomerAsIndividual(ctx context.Context, in *SetCustomerAsIndividualRequest, opts ...grpc.CallOption) (*SetCustomerAsIndividualResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCustomerAsIndividualResponse)
	err := c.cc.Invoke(ctx, CustomerService_SetCustomerAsIndividual_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) UpdateBusinessInfo(ctx context.Context, in *UpdateBusinessInfoRequest, opts ...grpc.CallOption) (*UpdateBusinessInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBusinessInfoResponse)
	err := c.cc.Invoke(ctx, CustomerService_UpdateBusinessInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) UpdateFinancialData(ctx context.Context, in *UpdateFinancialDataRequest, opts ...grpc.CallOption) (*UpdateFinancialDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFinancialDataResponse)
	err := c.cc.Invoke(ctx, CustomerService_UpdateFinancialData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) ApproveBusiness(ctx context.Context, in *ApproveBusinessRequest, opts ...grpc.CallOption) (*ApproveBusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveBusinessResponse)
	err := c.cc.Invoke(ctx, CustomerService_ApproveBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
// All implementations must embed UnimplementedCustomerServiceServer
// for forward compatibility.
//
// Customer service definition
type CustomerServiceServer interface {
	// Create Online Business
	CreateOnlineBusiness(context.Context, *CreateOnlineBusinessRequest) (*CreateOnlineBusinessResponse, error)
	// Update Corporate Customer National ID
	UpdateCorporateCustomerNationalID(context.Context, *UpdateCorporateCustomerNationalIDRequest) (*UpdateCorporateCustomerNationalIDResponse, error)
	// Set Customer As Individual
	SetCustomerAsIndividual(context.Context, *SetCustomerAsIndividualRequest) (*SetCustomerAsIndividualResponse, error)
	// Update Business Info
	UpdateBusinessInfo(context.Context, *UpdateBusinessInfoRequest) (*UpdateBusinessInfoResponse, error)
	// Update Financial Data
	UpdateFinancialData(context.Context, *UpdateFinancialDataRequest) (*UpdateFinancialDataResponse, error)
	// Approve Business
	ApproveBusiness(context.Context, *ApproveBusinessRequest) (*ApproveBusinessResponse, error)
	mustEmbedUnimplementedCustomerServiceServer()
}

// UnimplementedCustomerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerServiceServer struct{}

func (UnimplementedCustomerServiceServer) CreateOnlineBusiness(context.Context, *CreateOnlineBusinessRequest) (*CreateOnlineBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOnlineBusiness not implemented")
}
func (UnimplementedCustomerServiceServer) UpdateCorporateCustomerNationalID(context.Context, *UpdateCorporateCustomerNationalIDRequest) (*UpdateCorporateCustomerNationalIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCorporateCustomerNationalID not implemented")
}
func (UnimplementedCustomerServiceServer) SetCustomerAsIndividual(context.Context, *SetCustomerAsIndividualRequest) (*SetCustomerAsIndividualResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCustomerAsIndividual not implemented")
}
func (UnimplementedCustomerServiceServer) UpdateBusinessInfo(context.Context, *UpdateBusinessInfoRequest) (*UpdateBusinessInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBusinessInfo not implemented")
}
func (UnimplementedCustomerServiceServer) UpdateFinancialData(context.Context, *UpdateFinancialDataRequest) (*UpdateFinancialDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFinancialData not implemented")
}
func (UnimplementedCustomerServiceServer) ApproveBusiness(context.Context, *ApproveBusinessRequest) (*ApproveBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveBusiness not implemented")
}
func (UnimplementedCustomerServiceServer) mustEmbedUnimplementedCustomerServiceServer() {}
func (UnimplementedCustomerServiceServer) testEmbeddedByValue()                         {}

// UnsafeCustomerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerServiceServer will
// result in compilation errors.
type UnsafeCustomerServiceServer interface {
	mustEmbedUnimplementedCustomerServiceServer()
}

func RegisterCustomerServiceServer(s grpc.ServiceRegistrar, srv CustomerServiceServer) {
	// If the following call pancis, it indicates UnimplementedCustomerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerService_ServiceDesc, srv)
}

func _CustomerService_CreateOnlineBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOnlineBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateOnlineBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_CreateOnlineBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateOnlineBusiness(ctx, req.(*CreateOnlineBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_UpdateCorporateCustomerNationalID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCorporateCustomerNationalIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).UpdateCorporateCustomerNationalID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_UpdateCorporateCustomerNationalID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).UpdateCorporateCustomerNationalID(ctx, req.(*UpdateCorporateCustomerNationalIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_SetCustomerAsIndividual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCustomerAsIndividualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).SetCustomerAsIndividual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_SetCustomerAsIndividual_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).SetCustomerAsIndividual(ctx, req.(*SetCustomerAsIndividualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_UpdateBusinessInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBusinessInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).UpdateBusinessInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_UpdateBusinessInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).UpdateBusinessInfo(ctx, req.(*UpdateBusinessInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_UpdateFinancialData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFinancialDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).UpdateFinancialData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_UpdateFinancialData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).UpdateFinancialData(ctx, req.(*UpdateFinancialDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_ApproveBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).ApproveBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_ApproveBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).ApproveBusiness(ctx, req.(*ApproveBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerService_ServiceDesc is the grpc.ServiceDesc for CustomerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOnlineBusiness",
			Handler:    _CustomerService_CreateOnlineBusiness_Handler,
		},
		{
			MethodName: "UpdateCorporateCustomerNationalID",
			Handler:    _CustomerService_UpdateCorporateCustomerNationalID_Handler,
		},
		{
			MethodName: "SetCustomerAsIndividual",
			Handler:    _CustomerService_SetCustomerAsIndividual_Handler,
		},
		{
			MethodName: "UpdateBusinessInfo",
			Handler:    _CustomerService_UpdateBusinessInfo_Handler,
		},
		{
			MethodName: "UpdateFinancialData",
			Handler:    _CustomerService_UpdateFinancialData_Handler,
		},
		{
			MethodName: "ApproveBusiness",
			Handler:    _CustomerService_ApproveBusiness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
