// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: customer.proto

package customer

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create Online Business request message
type CreateOnlineBusinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebsiteName   string                 `protobuf:"bytes,1,opt,name=website_name,json=websiteName,proto3" json:"website_name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	EnamadId      string                 `protobuf:"bytes,3,opt,name=enamad_id,json=enamadId,proto3" json:"enamad_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOnlineBusinessRequest) Reset() {
	*x = CreateOnlineBusinessRequest{}
	mi := &file_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOnlineBusinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOnlineBusinessRequest) ProtoMessage() {}

func (x *CreateOnlineBusinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOnlineBusinessRequest.ProtoReflect.Descriptor instead.
func (*CreateOnlineBusinessRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOnlineBusinessRequest) GetWebsiteName() string {
	if x != nil {
		return x.WebsiteName
	}
	return ""
}

func (x *CreateOnlineBusinessRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateOnlineBusinessRequest) GetEnamadId() string {
	if x != nil {
		return x.EnamadId
	}
	return ""
}

func (x *CreateOnlineBusinessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Create Online Business response message
type CreateOnlineBusinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOnlineBusinessResponse) Reset() {
	*x = CreateOnlineBusinessResponse{}
	mi := &file_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOnlineBusinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOnlineBusinessResponse) ProtoMessage() {}

func (x *CreateOnlineBusinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOnlineBusinessResponse.ProtoReflect.Descriptor instead.
func (*CreateOnlineBusinessResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOnlineBusinessResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOnlineBusinessResponse) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

// Update Corporate Customer National ID request message
type UpdateCorporateCustomerNationalIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	NationalId    string                 `protobuf:"bytes,2,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCorporateCustomerNationalIDRequest) Reset() {
	*x = UpdateCorporateCustomerNationalIDRequest{}
	mi := &file_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCorporateCustomerNationalIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCorporateCustomerNationalIDRequest) ProtoMessage() {}

func (x *UpdateCorporateCustomerNationalIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCorporateCustomerNationalIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateCorporateCustomerNationalIDRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCorporateCustomerNationalIDRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateCorporateCustomerNationalIDRequest) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

// Update Corporate Customer National ID response message
type UpdateCorporateCustomerNationalIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCorporateCustomerNationalIDResponse) Reset() {
	*x = UpdateCorporateCustomerNationalIDResponse{}
	mi := &file_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCorporateCustomerNationalIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCorporateCustomerNationalIDResponse) ProtoMessage() {}

func (x *UpdateCorporateCustomerNationalIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCorporateCustomerNationalIDResponse.ProtoReflect.Descriptor instead.
func (*UpdateCorporateCustomerNationalIDResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCorporateCustomerNationalIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Set Customer As Individual request message
type SetCustomerAsIndividualRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCustomerAsIndividualRequest) Reset() {
	*x = SetCustomerAsIndividualRequest{}
	mi := &file_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCustomerAsIndividualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCustomerAsIndividualRequest) ProtoMessage() {}

func (x *SetCustomerAsIndividualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCustomerAsIndividualRequest.ProtoReflect.Descriptor instead.
func (*SetCustomerAsIndividualRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{4}
}

func (x *SetCustomerAsIndividualRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetCustomerAsIndividualRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// Set Customer As Individual response message
type SetCustomerAsIndividualResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCustomerAsIndividualResponse) Reset() {
	*x = SetCustomerAsIndividualResponse{}
	mi := &file_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCustomerAsIndividualResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCustomerAsIndividualResponse) ProtoMessage() {}

func (x *SetCustomerAsIndividualResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCustomerAsIndividualResponse.ProtoReflect.Descriptor instead.
func (*SetCustomerAsIndividualResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{5}
}

func (x *SetCustomerAsIndividualResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Update Business Info request message
type UpdateBusinessInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guild         string                 `protobuf:"bytes,1,opt,name=guild,proto3" json:"guild,omitempty"`
	LicenseId     string                 `protobuf:"bytes,2,opt,name=license_id,json=licenseId,proto3" json:"license_id,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	PhoneTech     string                 `protobuf:"bytes,4,opt,name=phone_tech,json=phoneTech,proto3" json:"phone_tech,omitempty"`
	PhoneBusiness string                 `protobuf:"bytes,5,opt,name=phone_business,json=phoneBusiness,proto3" json:"phone_business,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBusinessInfoRequest) Reset() {
	*x = UpdateBusinessInfoRequest{}
	mi := &file_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBusinessInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusinessInfoRequest) ProtoMessage() {}

func (x *UpdateBusinessInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusinessInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateBusinessInfoRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBusinessInfoRequest) GetGuild() string {
	if x != nil {
		return x.Guild
	}
	return ""
}

func (x *UpdateBusinessInfoRequest) GetLicenseId() string {
	if x != nil {
		return x.LicenseId
	}
	return ""
}

func (x *UpdateBusinessInfoRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *UpdateBusinessInfoRequest) GetPhoneTech() string {
	if x != nil {
		return x.PhoneTech
	}
	return ""
}

func (x *UpdateBusinessInfoRequest) GetPhoneBusiness() string {
	if x != nil {
		return x.PhoneBusiness
	}
	return ""
}

// Update Business Info response message
type UpdateBusinessInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBusinessInfoResponse) Reset() {
	*x = UpdateBusinessInfoResponse{}
	mi := &file_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBusinessInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusinessInfoResponse) ProtoMessage() {}

func (x *UpdateBusinessInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusinessInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateBusinessInfoResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBusinessInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Update Financial Data request message
type UpdateFinancialDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxId         string                 `protobuf:"bytes,1,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	Iban          string                 `protobuf:"bytes,2,opt,name=iban,proto3" json:"iban,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFinancialDataRequest) Reset() {
	*x = UpdateFinancialDataRequest{}
	mi := &file_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFinancialDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFinancialDataRequest) ProtoMessage() {}

func (x *UpdateFinancialDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFinancialDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateFinancialDataRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFinancialDataRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *UpdateFinancialDataRequest) GetIban() string {
	if x != nil {
		return x.Iban
	}
	return ""
}

// Update Financial Data response message
type UpdateFinancialDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFinancialDataResponse) Reset() {
	*x = UpdateFinancialDataResponse{}
	mi := &file_customer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFinancialDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFinancialDataResponse) ProtoMessage() {}

func (x *UpdateFinancialDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFinancialDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateFinancialDataResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateFinancialDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Approve Business request message
type ApproveBusinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveBusinessRequest) Reset() {
	*x = ApproveBusinessRequest{}
	mi := &file_customer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveBusinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveBusinessRequest) ProtoMessage() {}

func (x *ApproveBusinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveBusinessRequest.ProtoReflect.Descriptor instead.
func (*ApproveBusinessRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{10}
}

func (x *ApproveBusinessRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

// Approve Business response message
type ApproveBusinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveBusinessResponse) Reset() {
	*x = ApproveBusinessResponse{}
	mi := &file_customer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveBusinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveBusinessResponse) ProtoMessage() {}

func (x *ApproveBusinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveBusinessResponse.ProtoReflect.Descriptor instead.
func (*ApproveBusinessResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{11}
}

func (x *ApproveBusinessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_customer_proto protoreflect.FileDescriptor

const file_customer_proto_rawDesc = "" +
	"\n" +
	"\x0ecustomer.proto\x12\bcustomer\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x88\x01\n" +
	"\x1bCreateOnlineBusinessRequest\x12!\n" +
	"\fwebsite_name\x18\x01 \x01(\tR\vwebsiteName\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\tenamad_id\x18\x03 \x01(\tR\benamadId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"`\n" +
	"\x1cCreateOnlineBusinessResponse\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\"\xd0\x01\n" +
	"(UpdateCorporateCustomerNationalIDRequest\x12I\n" +
	"\vcustomer_id\x18\x01 \x01(\tB(\x92A%2\x15Customer ID to update\xd2\x01\vcustomer_idR\n" +
	"customerId\x12Y\n" +
	"\vnational_id\x18\x02 \x01(\tB8\x92A52%National ID of the corporate customer\xd2\x01\vnational_idR\n" +
	"nationalId\"\\\n" +
	")UpdateCorporateCustomerNationalIDResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\tB\x19\x92A\x162\x14Error message if anyR\x05error\"\xa7\x01\n" +
	"\x1eSetCustomerAsIndividualRequest\x12/\n" +
	"\auser_id\x18\x01 \x01(\tB\x16\x92A\x132\aUser ID\xd2\x01\auser_idR\x06userId\x12T\n" +
	"\vcustomer_id\x18\x02 \x01(\tB3\x92A02 Customer ID to set as individual\xd2\x01\vcustomer_idR\n" +
	"customerId\"R\n" +
	"\x1fSetCustomerAsIndividualResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\tB\x19\x92A\x162\x14Error message if anyR\x05error\"\xfb\x02\n" +
	"\x19UpdateBusinessInfoRequest\x12:\n" +
	"\x05guild\x18\x01 \x01(\tB$\x92A!2\x17Business guild/industry\xd2\x01\x05guildR\x05guild\x12D\n" +
	"\n" +
	"license_id\x18\x02 \x01(\tB%\x92A\"2\x13Business license ID\xd2\x01\n" +
	"license_idR\tlicenseId\x12?\n" +
	"\vpostal_code\x18\x03 \x01(\tB\x1e\x92A\x1b2\vPostal code\xd2\x01\vpostal_codeR\n" +
	"postalCode\x12G\n" +
	"\n" +
	"phone_tech\x18\x04 \x01(\tB(\x92A%2\x16Technical phone number\xd2\x01\n" +
	"phone_techR\tphoneTech\x12R\n" +
	"\x0ephone_business\x18\x05 \x01(\tB+\x92A(2\x15Business phone number\xd2\x01\x0ephone_businessR\rphoneBusiness\"M\n" +
	"\x1aUpdateBusinessInfoResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\tB\x19\x92A\x162\x14Error message if anyR\x05error\"\xa6\x01\n" +
	"\x1aUpdateFinancialDataRequest\x12>\n" +
	"\x06tax_id\x18\x01 \x01(\tB'\x92A$2\x19Tax identification number\xd2\x01\x06tax_idR\x05taxId\x12H\n" +
	"\x04iban\x18\x02 \x01(\tB4\x92A12(International Bank Account Number (IBAN)\xd2\x01\x04ibanR\x04iban\"N\n" +
	"\x1bUpdateFinancialDataResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\tB\x19\x92A\x162\x14Error message if anyR\x05error\"d\n" +
	"\x16ApproveBusinessRequest\x12J\n" +
	"\vbusiness_id\x18\x01 \x01(\tB)\x92A&2\x16Business ID to approve\xd2\x01\vbusiness_idR\n" +
	"businessId\"J\n" +
	"\x17ApproveBusinessResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\tB\x19\x92A\x162\x14Error message if anyR\x05error2\xc7\v\n" +
	"\x0fCustomerService\x12\xf6\x01\n" +
	"\x14CreateOnlineBusiness\x12%.customer.CreateOnlineBusinessRequest\x1a&.customer.CreateOnlineBusinessResponse\"\x8e\x01\x92Ab\n" +
	"\bCustomer\x12\x16Create Online Business\x1a>Creates a new online business profile with website information\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/rest/customer/online-business\x12\xa4\x02\n" +
	"!UpdateCorporateCustomerNationalID\x122.customer.UpdateCorporateCustomerNationalIDRequest\x1a3.customer.UpdateCorporateCustomerNationalIDResponse\"\x95\x01\x92Ac\n" +
	"\bCustomer\x12%Update Corporate Customer National ID\x1a0Updates the national ID for a corporate customer\x82\xd3\xe4\x93\x02):\x01*\x1a$/rest/customer/corporate/national-id\x12\xed\x01\n" +
	"\x17SetCustomerAsIndividual\x12(.customer.SetCustomerAsIndividualRequest\x1a).customer.SetCustomerAsIndividualResponse\"}\x92AV\n" +
	"\bCustomer\x12\x1aSet Customer As Individual\x1a.Sets a customer as an individual customer type\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/rest/customer/individual\x12\xf8\x01\n" +
	"\x12UpdateBusinessInfo\x12#.customer.UpdateBusinessInfoRequest\x1a$.customer.UpdateBusinessInfoResponse\"\x96\x01\x92Al\n" +
	"\bCustomer\x12\x14Update Business Info\x1aJUpdates business information including guild, license, and contact details\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/rest/customer/business-info\x12\xe2\x01\n" +
	"\x13UpdateFinancialData\x12$.customer.UpdateFinancialDataRequest\x1a%.customer.UpdateFinancialDataResponse\"~\x92AS\n" +
	"\bCustomer\x12\x15Update Financial Data\x1a0Updates financial data including tax ID and IBAN\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/rest/customer/financial-data\x12\xc3\x01\n" +
	"\x0fApproveBusiness\x12 .customer.ApproveBusinessRequest\x1a!.customer.ApproveBusinessResponse\"k\x92A>\n" +
	"\bCustomer\x12\x10Approve Business\x1a Approves a business registration\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/rest/customer/business/approveB\x99\x02\x92A\xe0\x01\x12\xb6\x01\n" +
	"\x14Customer Service API\x12\x18API for Customer service\"?\n" +
	"\vAPI Support\x12\x1bhttps://example.com/support\x1a\x13support@example.com*>\n" +
	"\n" +
	"Apache 2.0\x120https://www.apache.org/licenses/LICENSE-2.0.html2\x031.0*\x01\x022\x10application/json:\x10application/jsonZ3./services/customer/api/grpc/pb/src/golang;customerb\x06proto3"

var (
	file_customer_proto_rawDescOnce sync.Once
	file_customer_proto_rawDescData []byte
)

func file_customer_proto_rawDescGZIP() []byte {
	file_customer_proto_rawDescOnce.Do(func() {
		file_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customer_proto_rawDesc), len(file_customer_proto_rawDesc)))
	})
	return file_customer_proto_rawDescData
}

var file_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_customer_proto_goTypes = []any{
	(*CreateOnlineBusinessRequest)(nil),               // 0: customer.CreateOnlineBusinessRequest
	(*CreateOnlineBusinessResponse)(nil),              // 1: customer.CreateOnlineBusinessResponse
	(*UpdateCorporateCustomerNationalIDRequest)(nil),  // 2: customer.UpdateCorporateCustomerNationalIDRequest
	(*UpdateCorporateCustomerNationalIDResponse)(nil), // 3: customer.UpdateCorporateCustomerNationalIDResponse
	(*SetCustomerAsIndividualRequest)(nil),            // 4: customer.SetCustomerAsIndividualRequest
	(*SetCustomerAsIndividualResponse)(nil),           // 5: customer.SetCustomerAsIndividualResponse
	(*UpdateBusinessInfoRequest)(nil),                 // 6: customer.UpdateBusinessInfoRequest
	(*UpdateBusinessInfoResponse)(nil),                // 7: customer.UpdateBusinessInfoResponse
	(*UpdateFinancialDataRequest)(nil),                // 8: customer.UpdateFinancialDataRequest
	(*UpdateFinancialDataResponse)(nil),               // 9: customer.UpdateFinancialDataResponse
	(*ApproveBusinessRequest)(nil),                    // 10: customer.ApproveBusinessRequest
	(*ApproveBusinessResponse)(nil),                   // 11: customer.ApproveBusinessResponse
}
var file_customer_proto_depIdxs = []int32{
	0,  // 0: customer.CustomerService.CreateOnlineBusiness:input_type -> customer.CreateOnlineBusinessRequest
	2,  // 1: customer.CustomerService.UpdateCorporateCustomerNationalID:input_type -> customer.UpdateCorporateCustomerNationalIDRequest
	4,  // 2: customer.CustomerService.SetCustomerAsIndividual:input_type -> customer.SetCustomerAsIndividualRequest
	6,  // 3: customer.CustomerService.UpdateBusinessInfo:input_type -> customer.UpdateBusinessInfoRequest
	8,  // 4: customer.CustomerService.UpdateFinancialData:input_type -> customer.UpdateFinancialDataRequest
	10, // 5: customer.CustomerService.ApproveBusiness:input_type -> customer.ApproveBusinessRequest
	1,  // 6: customer.CustomerService.CreateOnlineBusiness:output_type -> customer.CreateOnlineBusinessResponse
	3,  // 7: customer.CustomerService.UpdateCorporateCustomerNationalID:output_type -> customer.UpdateCorporateCustomerNationalIDResponse
	5,  // 8: customer.CustomerService.SetCustomerAsIndividual:output_type -> customer.SetCustomerAsIndividualResponse
	7,  // 9: customer.CustomerService.UpdateBusinessInfo:output_type -> customer.UpdateBusinessInfoResponse
	9,  // 10: customer.CustomerService.UpdateFinancialData:output_type -> customer.UpdateFinancialDataResponse
	11, // 11: customer.CustomerService.ApproveBusiness:output_type -> customer.ApproveBusinessResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_customer_proto_init() }
func file_customer_proto_init() {
	if File_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customer_proto_rawDesc), len(file_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customer_proto_goTypes,
		DependencyIndexes: file_customer_proto_depIdxs,
		MessageInfos:      file_customer_proto_msgTypes,
	}.Build()
	File_customer_proto = out.File
	file_customer_proto_goTypes = nil
	file_customer_proto_depIdxs = nil
}
