// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: user-backoffice.proto

package user_backoffice

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserBackofficeService_ExampleMethod_FullMethodName = "/user_backoffice.UserBackofficeService/ExampleMethod"
)

// UserBackofficeServiceClient is the client API for UserBackofficeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Example service definition
type UserBackofficeServiceClient interface {
	// Example method
	ExampleMethod(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error)
}

type userBackofficeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserBackofficeServiceClient(cc grpc.ClientConnInterface) UserBackofficeServiceClient {
	return &userBackofficeServiceClient{cc}
}

func (c *userBackofficeServiceClient) ExampleMethod(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExampleResponse)
	err := c.cc.Invoke(ctx, UserBackofficeService_ExampleMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserBackofficeServiceServer is the server API for UserBackofficeService service.
// All implementations must embed UnimplementedUserBackofficeServiceServer
// for forward compatibility.
//
// Example service definition
type UserBackofficeServiceServer interface {
	// Example method
	ExampleMethod(context.Context, *ExampleRequest) (*ExampleResponse, error)
	mustEmbedUnimplementedUserBackofficeServiceServer()
}

// UnimplementedUserBackofficeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserBackofficeServiceServer struct{}

func (UnimplementedUserBackofficeServiceServer) ExampleMethod(context.Context, *ExampleRequest) (*ExampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExampleMethod not implemented")
}
func (UnimplementedUserBackofficeServiceServer) mustEmbedUnimplementedUserBackofficeServiceServer() {}
func (UnimplementedUserBackofficeServiceServer) testEmbeddedByValue()                               {}

// UnsafeUserBackofficeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserBackofficeServiceServer will
// result in compilation errors.
type UnsafeUserBackofficeServiceServer interface {
	mustEmbedUnimplementedUserBackofficeServiceServer()
}

func RegisterUserBackofficeServiceServer(s grpc.ServiceRegistrar, srv UserBackofficeServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserBackofficeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserBackofficeService_ServiceDesc, srv)
}

func _UserBackofficeService_ExampleMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBackofficeServiceServer).ExampleMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserBackofficeService_ExampleMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBackofficeServiceServer).ExampleMethod(ctx, req.(*ExampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserBackofficeService_ServiceDesc is the grpc.ServiceDesc for UserBackofficeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserBackofficeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_backoffice.UserBackofficeService",
	HandlerType: (*UserBackofficeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExampleMethod",
			Handler:    _UserBackofficeService_ExampleMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-backoffice.proto",
}
