// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: user-backoffice.proto

package user_backoffice

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Example request message
type ExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         string                 `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleRequest) Reset() {
	*x = ExampleRequest{}
	mi := &file_user_backoffice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleRequest) ProtoMessage() {}

func (x *ExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_backoffice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleRequest.ProtoReflect.Descriptor instead.
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return file_user_backoffice_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleRequest) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

// Example response message
type ExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	mi := &file_user_backoffice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_backoffice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_user_backoffice_proto_rawDescGZIP(), []int{1}
}

func (x *ExampleResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_user_backoffice_proto protoreflect.FileDescriptor

const file_user_backoffice_proto_rawDesc = "" +
	"\n" +
	"\x15user-backoffice.proto\x12\x0fuser_backoffice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"F\n" +
	"\x0eExampleRequest\x124\n" +
	"\x05param\x18\x01 \x01(\tB\x1e\x92A\x1b2\x11Example parameter\xd2\x01\x05paramR\x05param\">\n" +
	"\x0fExampleResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\tB\x13\x92A\x102\x0eExample resultR\x06result2\xd4\x01\n" +
	"\x15UserBackofficeService\x12\xba\x01\n" +
	"\rExampleMethod\x12\x1f.user_backoffice.ExampleRequest\x1a .user_backoffice.ExampleResponse\"f\x92A;\n" +
	"\x0eUserBackoffice\x12\x0eExample Method\x1a\x19This is an example method\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/rest/user/backoffice/exampleB\xb3\x02\x92A\xec\x01\x12\xc2\x01\n" +
	"\x1aUserBackoffice Service API\x12\x1eAPI for UserBackoffice service\"?\n" +
	"\vAPI Support\x12\x1bhttps://example.com/support\x1a\x13support@example.com*>\n" +
	"\n" +
	"Apache 2.0\x120https://www.apache.org/licenses/LICENSE-2.0.html2\x031.0*\x01\x022\x10application/json:\x10application/jsonZA./services/user-backoffice/api/grpc/pb/src/golang;user_backofficeb\x06proto3"

var (
	file_user_backoffice_proto_rawDescOnce sync.Once
	file_user_backoffice_proto_rawDescData []byte
)

func file_user_backoffice_proto_rawDescGZIP() []byte {
	file_user_backoffice_proto_rawDescOnce.Do(func() {
		file_user_backoffice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_backoffice_proto_rawDesc), len(file_user_backoffice_proto_rawDesc)))
	})
	return file_user_backoffice_proto_rawDescData
}

var file_user_backoffice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_backoffice_proto_goTypes = []any{
	(*ExampleRequest)(nil),  // 0: user_backoffice.ExampleRequest
	(*ExampleResponse)(nil), // 1: user_backoffice.ExampleResponse
}
var file_user_backoffice_proto_depIdxs = []int32{
	0, // 0: user_backoffice.UserBackofficeService.ExampleMethod:input_type -> user_backoffice.ExampleRequest
	1, // 1: user_backoffice.UserBackofficeService.ExampleMethod:output_type -> user_backoffice.ExampleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_backoffice_proto_init() }
func file_user_backoffice_proto_init() {
	if File_user_backoffice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_backoffice_proto_rawDesc), len(file_user_backoffice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_backoffice_proto_goTypes,
		DependencyIndexes: file_user_backoffice_proto_depIdxs,
		MessageInfos:      file_user_backoffice_proto_msgTypes,
	}.Build()
	File_user_backoffice_proto = out.File
	file_user_backoffice_proto_goTypes = nil
	file_user_backoffice_proto_depIdxs = nil
}
