// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: user.proto

package user

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsShahkarValidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NationalCode  string                 `protobuf:"bytes,2,opt,name=national_code,json=nationalCode,proto3" json:"national_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsShahkarValidRequest) Reset() {
	*x = IsShahkarValidRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsShahkarValidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsShahkarValidRequest) ProtoMessage() {}

func (x *IsShahkarValidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsShahkarValidRequest.ProtoReflect.Descriptor instead.
func (*IsShahkarValidRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *IsShahkarValidRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *IsShahkarValidRequest) GetNationalCode() string {
	if x != nil {
		return x.NationalCode
	}
	return ""
}

type IsShahkarValidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsShahkarValidResponse) Reset() {
	*x = IsShahkarValidResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsShahkarValidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsShahkarValidResponse) ProtoMessage() {}

func (x *IsShahkarValidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsShahkarValidResponse.ProtoReflect.Descriptor instead.
func (*IsShahkarValidResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *IsShahkarValidResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

// Example request message
type ExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         string                 `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleRequest) Reset() {
	*x = ExampleRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleRequest) ProtoMessage() {}

func (x *ExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleRequest.ProtoReflect.Descriptor instead.
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ExampleRequest) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

// Example response message
type ExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *ExampleResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"T\n" +
	"\x15IsShahkarValidRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12#\n" +
	"\rnational_code\x18\x02 \x01(\tR\fnationalCode\"3\n" +
	"\x16IsShahkarValidResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"&\n" +
	"\x0eExampleRequest\x12\x14\n" +
	"\x05param\x18\x01 \x01(\tR\x05param\")\n" +
	"\x0fExampleResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\x9c\x02\n" +
	"\vUserService\x129\n" +
	"\n" +
	"MethodCore\x12\x14.user.ExampleRequest\x1a\x15.user.ExampleResponse\x12A\n" +
	"\x12MethodForDashboard\x12\x14.user.ExampleRequest\x1a\x15.user.ExampleResponse\x12B\n" +
	"\x13MethodForBackoffice\x12\x14.user.ExampleRequest\x1a\x15.user.ExampleResponse\x12K\n" +
	"\x0eIsShahkarValid\x12\x1b.user.IsShahkarValidRequest\x1a\x1c.user.IsShahkarValidResponseB-Z+./services/user/api/grpc/pb/src/golang;userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_proto_goTypes = []any{
	(*IsShahkarValidRequest)(nil),  // 0: user.IsShahkarValidRequest
	(*IsShahkarValidResponse)(nil), // 1: user.IsShahkarValidResponse
	(*ExampleRequest)(nil),         // 2: user.ExampleRequest
	(*ExampleResponse)(nil),        // 3: user.ExampleResponse
}
var file_user_proto_depIdxs = []int32{
	2, // 0: user.UserService.MethodCore:input_type -> user.ExampleRequest
	2, // 1: user.UserService.MethodForDashboard:input_type -> user.ExampleRequest
	2, // 2: user.UserService.MethodForBackoffice:input_type -> user.ExampleRequest
	0, // 3: user.UserService.IsShahkarValid:input_type -> user.IsShahkarValidRequest
	3, // 4: user.UserService.MethodCore:output_type -> user.ExampleResponse
	3, // 5: user.UserService.MethodForDashboard:output_type -> user.ExampleResponse
	3, // 6: user.UserService.MethodForBackoffice:output_type -> user.ExampleResponse
	1, // 7: user.UserService.IsShahkarValid:output_type -> user.IsShahkarValidResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
